server:
  port: 8890
nacos:
  discovery:
    server-addr: 47.115.166.117:8848
  config:
    server-addr: 47.115.166.117:8848
metis:
  accessKey: QdtxCxaz0M6uWZ48s-UGq_hKbhUuXIEKV0c4b_db
  secretKey: 2ZQtoKP1soQ9MWnAxwTdxm-3mv-EqgzqDcYuxBOC
  hidePath: D:/fileUpload/