spring:
  application:
    name: metis-client
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
management:
  endpoints:
    web:
      exposure:
        include: 'info,health'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
      sensitive: false
    restart:
      enabled: false
jasypt:
  encryptor:
    password: hB0_kA1@eD05eE0`aA0(kB0)cG2+jE
server:
  port: 8891
nacos:
  discovery:
    server-addr: 47.115.166.117:8848
  config:
    server-addr: 47.115.166.117:8848